twilio/config/routes.rb
Rails.application.routes.draw do
  resources :instructors
  
  root 'instructors#index'
   
  get 'instructors/:id/text' => 'instructors#text', as: :text

end

twilio/app/models/instructor.rb
class Instructor < ActiveRecord::Base
end

twilio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

twilio/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  def text
    @instructor = set_instructor
    @message = params[:message]
    
    account_sid = "AC3cf1284634368f7cda58c785e31c95d8"
    # from api credentials can find at dashboard/credentials
    auth_token = "572c7c5e5d6192fc42642f7db099495e"
    #from api key credentials can find at dashboard/credentials
    client = Twilio::REST::Client.new account_sid, auth_token
    # here we pull in the variables we just set up
    
    from = "7048156779"
    # twilio number
    
    client.account.messages.create(
      :from => from,
      :to => "+1" + @instructor.phone,
      :body => @message
      )
      
      flash[:notice] = "Text to send to instructor. Now go study!"
      redirect_to :action => "show", :id => @instructor.id
  end
  
  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :phone)
    end
end

twilio/app/helpers/application_helper.rb
module ApplicationHelper
end

twilio/app/helpers/instructors_helper.rb
module InstructorsHelper
end

twilio/app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twilio/app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

twilio/app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.phone %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

twilio/app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

twilio/app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @instructor.phone %>
</p>

<%= form_tag("/instructors/" + @instructor.id.to_s + "/text", method: "get") do %>
    <%= label_tag(:message, "message")%>
    <%=text_field_tag(:message) %>
    <%=submit_tag("Send Text!") %>
  <%end %>
<br>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>

twilio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twilio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>